### ISSUE TITLE
error on latest version

### ISSUE THREAD

**Issue by mgelbart** [kohler/johnkimble#2]
When running `node johnkimble` I get the following error (not immediately, but when I go to the URL in Chrome):

```
/Users/mgelbart/Desktop/johnkimble/johnkimble.js:262
    if ((i = this.url.match(/(?:\/\/[^\/]+)?(\/.*\/$)/)))
                     ^
TypeError: Cannot read property 'match' of undefined
    at new Course (/Users/mgelbart/Desktop/johnkimble/johnkimble.js:262:22)
    at create_course (/Users/mgelbart/Desktop/johnkimble/johnkimble.js:836:22)
    at Server.server (/Users/mgelbart/Desktop/johnkimble/johnkimble.js:1115:32)
    at Server.emit (events.js:110:17)
    at HTTPParser.parserOnIncoming [as onIncoming] (_http_server.js:491:12)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:111:23)
    at Socket.socketOnData (_http_server.js:343:22)
    at Socket.emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:163:16)
    at Socket.Readable.push (_stream_readable.js:126:10)
```

if I use the version from the previous commit, d9bdcb2979be6a83bf06db5548ba68a4bce64b87, then everything is fine.

FYI the output when I type `node --version` is `v0.12.7` and I'm using Mac OS 10.11.6.

**Comment by kohler** [comment]
Maybe that fixed it?...

**Comment by mgelbart** [comment]
I think so -- I'm now able to run the latest version, cf9003a1f2a64047b3d3ad6ba6a607e0ced422fd. Thanks.

**Comment by mgelbart** [comment]
Actually, I'm having a separate problem with this latest version. When I run the server on my laptop I can interact with it from the browser on my laptop, no problems (this is why I said it was ok in my last message). But when I try from my phone or iPad it doesn't work. The phone/iPad sees _something_: for example it sees the STOP and GO options when the server is running and gives 404 when the server is not running, so there's definitely some interaction. But there are two problems:

1. The phone/iPad only sees STOP and GO; for some reason ASK is missing.
2. More importantly, I can't press STOP or GO; nothing happens when I do so.

Again, going back to commit d9bdcb2 solves the problem (keeping everything else the same). l'm happy to continue using that version... unless you've added some important changes since then?

**Comment by kohler** [comment]
Can you please send me or attach your serverconfig.js?

**Comment by mgelbart** [comment]
I don't think I have a file with this name. Where should I look for it?

Also, FYI I didn't change any options or modify any files. For both d9bdcb2 and cf9003a I just cloned the repo and ran `node johnkimble --fg`.

**Comment by kohler** [comment]
You added no files at all? OK. That gives me a place to start.

**Comment by kohler** [comment]
Maybe try latest?

**Comment by mgelbart** [comment]
My non-rigorous testing indicates this did the trick. Thanks 👍
